# Generated by Django 5.2.3 on 2025-08-17 16:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('musica', '0002_tipomusical_alter_artista_options_artista_biografia_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eventos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('slug', models.SlugField(blank=True, max_length=250, unique_for_date='fecha_evento')),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_evento', models.DateTimeField()),
                ('lugar', models.CharField(max_length=200)),
                ('direccion', models.CharField(blank=True, max_length=250, null=True)),
                ('fecha_publicacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('imagen_evento', models.ImageField(blank=True, null=True, upload_to='eventos_imagenes/')),
                ('activo', models.BooleanField(default=True, help_text='Indica si el evento está activo para venta de entradas')),
                ('artistas_participantes', models.ManyToManyField(blank=True, related_name='eventos_participados', to='musica.artista')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['fecha_publicacion'],
            },
        ),
    ]
