# Generated by Django 5.2.3 on 2025-08-17 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventos',
            name='artistas_participantes',
        ),
        migrations.RemoveField(
            model_name='novedad',
            name='artista_relacionado',
        ),
        migrations.RemoveField(
            model_name='novedad',
            name='autor',
        ),
        migrations.RenameField(
            model_name='comentario',
            old_name='autor_comentario',
            new_name='autor',
        ),
        migrations.DeleteModel(
            name='Artista',
        ),
        migrations.DeleteModel(
            name='TipoMusical',
        ),
        migrations.DeleteModel(
            name='Eventos',
        ),
        migrations.DeleteModel(
            name='Novedad',
        ),
    ]
