# Generated by Django 5.2.3 on 2025-07-30 22:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
        ('musica', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoMusical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Rock, Pop, Jazz', max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Tipo Musical',
                'verbose_name_plural': 'Tipos Musicales',
            },
        ),
        migrations.CreateModel(
            name='Eventos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('slug', models.SlugField(blank=True, max_length=250, unique_for_date='fecha_evento')),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_evento', models.DateTimeField()),
                ('lugar', models.CharField(max_length=200)),
                ('direccion', models.CharField(blank=True, max_length=250, null=True)),
                ('fecha_publicacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('imagen_evento', models.ImageField(blank=True, null=True, upload_to='eventos_imagenes/')),
                ('activo', models.BooleanField(default=True, help_text='Indica si el evento está activo para venta de entradas')),
                ('artistas_participantes', models.ManyToManyField(blank=True, related_name='eventos_participados', to='musica.artista')),
            ],
            options={
                'verbose_name': 'Novedad',
                'verbose_name_plural': 'Novedades',
                'ordering': ['-fecha_publicacion'],
            },
        ),
        migrations.CreateModel(
            name='Novedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=250)),
                ('slug', models.SlugField(blank=True, max_length=250, unique_for_date='fecha_publicacion')),
                ('contenido', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_publicacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('imagen_destacada', models.ImageField(blank=True, null=True, upload_to='novedades_imagenes/')),
                ('publicado', models.BooleanField(default=False)),
                ('artista_relacionado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='novedades', to='musica.artista')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='novedades_creadas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Artista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('biografia', models.TextField(blank=True, null=True)),
                ('imagen_perfil', models.ImageField(blank=True, null=True, upload_to='artistas_imagenes/')),
                ('sitio_web', models.URLField(blank=True, null=True)),
                ('tipos_musicales', models.ManyToManyField(blank=True, related_name='artistas', to='blogapp.tipomusical')),
            ],
            options={
                'verbose_name': 'Artista',
                'verbose_name_plural': 'Artistas',
                'ordering': ['nombre'],
            },
        ),
    ]
