# Generated by Django 5.2.3 on 2025-08-20 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_remove_eventos_artistas_participantes_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentario',
            old_name='autor',
            new_name='autor_comentario',
        ),
        migrations.AddField(
            model_name='post',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='posts/'),
        ),
    ]
