# Generated by Django 5.2.3 on 2025-08-17 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musica', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoMusical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Rock, Pop, Jazz', max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Tipo Musical',
                'verbose_name_plural': 'Tipos Musicales',
            },
        ),
        migrations.AlterModelOptions(
            name='artista',
            options={'ordering': ['nombre'], 'verbose_name': 'Artista', 'verbose_name_plural': 'Artistas'},
        ),
        migrations.AddField(
            model_name='artista',
            name='biografia',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='artista',
            name='imagen_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='artistas_imagenes/'),
        ),
        migrations.AddField(
            model_name='artista',
            name='sitio_web',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='artista',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='artista',
            name='nombre',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AddField(
            model_name='artista',
            name='tipos_musicales',
            field=models.ManyToManyField(blank=True, related_name='artistas', to='musica.tipomusical'),
        ),
    ]
