# Generated by Django 5.2.3 on 2025-08-17 16:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('musica', '0002_tipomusical_alter_artista_options_artista_biografia_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Novedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=250)),
                ('slug', models.SlugField(blank=True, max_length=250, unique_for_date='fecha_publicacion')),
                ('contenido', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_publicacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('imagen_destacada', models.ImageField(blank=True, null=True, upload_to='novedades_imagenes/')),
                ('publicado', models.BooleanField(default=False)),
                ('artista_relacionado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='novedades', to='musica.artista')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='novedades_creadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Novedad',
                'verbose_name_plural': 'Novedades',
                'ordering': ['-fecha_publicacion'],
            },
        ),
    ]
